### ISSUE TITLE
Published docs are wrong

### ISSUE THREAD

**Issue by joakin** [loop-recur/lambdajs#8]
Hi, I was looking at the library and looking at the docs, and the sidebar is all messed up. 
Inside the Array header there are the array methods, regexp, object, number and string methods all mixed up.

From what I've seen there is no src for the docs, the html is hand edited. Whats the workflow with that? How do you generate the syntax highlighted code?

**Comment by DrBoolean** [comment]
Hi Joakin! Ha, i didn't notice that until just now.

@casperin originally created the docs so i'm not sure what he used.

I'd been watching ramda's doc discussion. Perhaps, i'll use what they decide on - doesn't really matter to me.

I didn't place too much emphasis on the docs as they are just the standard ecmascript fn's with the object as the last arg. I do see the importance, however, and should up my game there.

**Comment by joakin** [comment]
If we get to know what tool was used, I could try and make a pull request
with a npm run docs entry with the command and try to fix the docs. I've
been investigating but i'm not finding anything promising.

How do you feel about JSDoc comments? (I don't like them much, but it seems
that most tooling revolves around them)

**Comment by DrBoolean** [comment]
I once wrote a processor to convert type signatures to jsdoc style comments. Maybe i'll try to find that...

Any help would be much appreciated - I don't have any preference to a particular doc generator or style.

I'll see if Gorm chimes in with what he originally used. He/we had been grabbing mozilla ecmascript examples and docs for the most part so I'm not sure how he got that going.

**Comment by joakin** [comment]
I'm closing this for now, it's been 2 years. If there's more interest we'll reopen.
